package seeders

import (
	D "docker/database"
	M "docker/models"
	"math/rand"
	"time"
)

func LawSeeder() {
	rand.Seed(time.Now().UnixNano())
	x := `<p dir="RTL" style="text-align:right; margin-bottom:11px"><strong>ماده1 -تعریف</strong><br />كانون فرهنگی و تربیتی دانشآموزان به مركزی اطلاق میشود كه برای اجرای برنامـه هـا و<br />فعالیتهای فرهنگی، ادبی، هنری، ورزشی، اجتماعی، علمی و مهارتی در جهت رشد و شكوفایی<br />استعدادهای نوجوانان و جوانان دانشآموز به ویژه دورههای راهنمـا یی تحصـیلی و متوسـطه در<br />سراسر كشور تشكیل میگردد<br /><strong>ماده 2 -هدف</strong><br />الف- بارور كردن اوقات فراغت دانشآموزان به منظور رشد و شكوفایی استعدادهای معنوی،<br />فكری، جسمی و عاطفی آنان از طریق اجرای برنامهها و فعالیـت هـای فرهنگـ ی، ادبـ ی، هنـر ی،<br />ورزشی، اجتماعی، علمی و مهارتی<br />ب- پرورش تقویت روحیه تعاون و اخوت دینـ ی و ایجـاد همبسـتگیی بـ ین دانـش آمـوزان و<br />آموختن روش زندگی اجتماعی به آنان بر اساس موازین اسلامی<br /><strong>فصل دوم- خط مشی، اصول برنامهها و شیوه تأسیس كانون فرهنگی و تربیتی<br />ماده 3</strong> -خط مشی و اصول برنامهریزی كانونهای فرهنگی و تربیتـ ی توسـط معـاون پرورشـ ی<br />پیشنهاد میشود و پس از تأیید وزیر آموزشوپرورش اجرا میگردد<br /><strong>ماده 4 </strong>-تأسیسكانون فرهنگی و تربیتی در هر شهر، شهرستان، منطقه و ناحیه بنا به پیشنهاد<br />مدیركل استان مربوط و موافقـت معـاون پرورشـی وزارت آمـوزش وپـرورش در قالـب<br />برنامهها و اعتبارات مصوب خواهد بود</p>`
	// statutes := []string{ // type 1
	// 	"اساسنامه مصوبه شورای شهر درباره شهرسازی",
	// 	"اساسنامه برابری جنسیتی در محیط کاری",
	// 	"اساسنامه حقوق بیماران در بیمارستان‌ها",
	// 	"اساسنامه تشکیل تعاونی‌های تولیدکننده",
	// 	"اساسنامه تنظیم و نظارت بر بازی‌های اینترنتی",
	// 	"اساسنامه محافظت از حیوانات بی‌سرپرست",
	// 	"اساسنامه تأمین اجتماعی بیماران کرونا",
	// 	"اساسنامه تحریم‌های اقتصادی آمریکا علیه ایران",
	// 	"حمایت از کارآفرینان علیه رانت دولتی",
	// 	"اساسنامه حقوق کارگران در صنایع سنگین",
	// 	"حقوق جانبازان و افراد دارای معلولیت",
	// 	"اساسنامه برقراری عدالت در دادگاه‌های کیفری",
	// 	"بررسی حقوق پایه‌ی معلمان و اعمال بهبودی‌های لازم",
	// 	"حمایت از سیاست‌های خودکارآمدی در کارخانه و تولید",
	// 	"ارتقای آگاهی مردم از حقوق زبان‌آموزان توسط مدارس",
	// 	"قوانین حفاظت از نهادهای اقتصادی و سرمایه‌گذاری",
	// 	"اساسنامه تنظیم و مدیریت در سیستم بهداشتی کشور",
	// 	"حقوق کودکان و تضمین دسترسی آنان به تحصیل در مدارس",
	// 	"اساسنامه محافظت از خانواده‌های کم درآمد",
	// 	"محافظت از حریم شخصی شهروندان در فضای مجازی",
	// 	"حقوق زنان و مبارزه با خشونت علیه آنان",
	// 	"تعیین اصول اخلاقی برای کارمندان دولت",
	// 	"حفاظت از محیط زیست و تحریم شرکت‌های آلاینده",
	// 	"ارتقاء سطح تحصیلی جوانان و حمایت از پرورش استعدادهای خلاق",
	// 	"اساسنامه دسترسی آسان به خدمات پزشکی برای سالمندان",
	// 	"توسعه فرهنگ کتاب‌خوانی و ترویج کتاب در جامعه",
	// 	"حفاظت از حریم خصوصی شهروندان طبق ماده ۴۴ اساسنامه اساسی",
	// 	"تضمین حق برابری در استخدام و لغو تمایز و تبعیض نژادی",
	// 	"تدوین دستورالعمل جدی برای مقابله با فساد اداری",
	// 	"اساسنامه تشدید مجازات در قتل عاملان تروریستی و مجرمین جنای",
	// }
	// regulations := []string{ // type 2
	// 	"آیین نامه جدید حقوق بشر",
	// 	"آیین نامه حقوق بیمه‌ای",
	// 	"آیین نامه حقوق مشاوره حقوقی",
	// 	"آیین نامه حقوق وکالت",
	// 	"آیین نامه حقوق مالیاتی",
	// 	"آیین نامه حقوق کار",
	// 	"آیین نامه حقوق خانواده",
	// 	"آیین نامه حقوق ملکی",
	// 	"آیین نامه حقوق کیفری",
	// 	"آیین نامه حقوق تجارت بین الملل",
	// 	"آیین نامه حقوق تحول اداری",
	// 	"آیین نامه حقوق امور خارجه",
	// 	"آیین نامه حقوق فرهنگی",
	// 	"آیین نامه حقوق سیاسی",
	// 	"آیین نامه حقوق اداری",
	// 	"آیین نامه حقوق توسعه کشور",
	// 	"آیین نامه حقوق کارگزینی",
	// 	"آیین نامه حقوق تعلیم و تربیت",
	// 	"آیین نامه حقوق حقوق بشر",
	// 	"آیین نامه حقوق مدیریت منابع انسانی",
	// 	"آیین نامه حقوق گردشگری",
	// 	"آیین نامه حقوق دفاع از مصلحت ملی",
	// 	"آیین نامه حقوق برق و انرژی",
	// 	"آیین نامه حقوق حمل و نقل و ترافیک",
	// 	"آیین نامه حقوق برنامه ریزی شهری",
	// 	"آیین نامه حقوق برنامه ریزی و مهندسی شهری",
	// 	"آیین نامه حقوق صنعت و معدن",
	// 	"آیین نامه حقوق محیط زیست",
	// 	"آیین نامه حقوق بدون مرز",
	// 	"آیین نامه حقوق تحول فناوری",
	// 	"آیین نامه حقوق شیلات و دامپروری",
	// 	"آیین نامه حقوق ارتباطات و فناوری اطلاعات",
	// 	"آیین نامه حقوق برقراری قراردادها",
	// 	"آیین نامه حقوق حریم خصوصی",
	// 	"آیین نامه حقوق تجارت الکترونیک",
	// 	"آیین نامه حقوق رقابت و تقلید",
	// 	"آیین نامه حقوق کار به صورت آنلاین",
	// 	"آیین نامه حقوق برچسب گذاری و نشانه گذاری",
	// 	"آیین نامه حقوق ویزا و مهاجرت",
	// 	"آیین نامه کانون زبان ایران",
	// 	"آیین نامه ارزشیابی درس تربیت بدنی",
	// 	"آیین نامه اعطای دیپلم افتخاری به جانبازان",
	// 	"آیین نامه ارزشیابی مدارک تحصیلی مدارش کشور های خارجی",
	// 	"آیین نامه جدید حقوق بشر",
	// 	"قانون جدید در مورد حمایت از کارگران",
	// 	"آیین نامه صدور پاسپورت",
	// 	"قانون جدید در مورد بیمه سلامت",
	// 	"آیین نامه مالیاتی برای کسب‌وکارها",
	// 	"قانون جدید در مورد حقوق مسلمانان",
	// 	"آیین نامه حمایت از زنان به عنوان تولیدکنندگان",
	// 	"قانون جدید در مورد طلاق و تفکیک ازدواج",
	// 	"آیین نامه جدید برای صدور ویزا به خارجیان",
	// 	"قانون جدید در مورد حمایت از کودکان",
	// 	"آیین نامه جدید در مورد رعایت حقوق شهروندی",
	// 	"قانون جدید در مورد داوری تجاری بین المللی",
	// 	"آیین نامه جدید برای تجارت الکترونیکی",
	// 	"قانون جدید در مورد حمایت از کارکنان معلول",
	// 	"آیین نامه جدید در مورد خرید و فروش املاک",
	// 	"قانون جدید در مورد حمایت از محیط زیست",
	// 	"آیین نامه جدید در مورد آزمون‌های دانشگاهی",
	// 	"قانون جدید در مورد حقوق مالکیت فکری",
	// 	"آیین نامه جدید در مورد تعرفه های پستی",
	// 	"قانون جدید در مورد حمایت از کسب‌وکارهای کوچک و متوسط",
	// 	"آیین نامه جدید در مورد حسابداری اسلامی",
	// 	"قانون جدید در مورد مدیریت ارتباط با مشتریان",
	// 	"آیین نامه جدید در مورد نحوه استفاده از مواد مخدر",
	// 	"قانون جدید در مورد حمایت از تولیدکنندگان محلی",
	// 	"آیین نامه جدید در مورد مسابقات ورزشی",
	// 	"قانون جدید در مورد حقوق حیوانات",
	// }
	enactments := []string{
		// "شفافیت در آیین‌نامه‌های کارمندی دولتی",
		// "نظام رتبه‌بندی و منابع انسانی دولتی",
		// "قانون الحاق تحصیل دانشجویان افغانی به دانشگاه‌های ایران",
		// "طرح‌های پژوهشی و فناوری در حوزه کشاورزی و محیط‌زیست",
		// "حمایت از کودکان خیابانی و ایجاد نگرش اجتماعی مثبت در قبال آنان",
		// "حفظ حریم شخصی و اطلاعات شخصی در فضای مجازی",
		// "حمل و نقل عمومی و راه اندازی خطوط مترو و اتوبوس",
		// "حمایت از کسب و کارهای کوچک و متوسط",
		// "ارتباط بین دانشگاه و صنعت در حوزه تحقیقات علمی و فناوری",
		// "توسعه صنعت گردشگری، هتلداری و صنایع مرتبط",
		// "استفاده از انرژی‌های تجدیدپذیر در تامین انرژی",
		// "ترویج کارآفرینی و شناخت برندها و ایده‌های نوین",
		// "تنظیم قوانین و محدودیت‌های شربت‌فروشی در محل‌های عمومی",
		// "توسعه فضای سبز در شهرها و محل‌های عمومی",
		// "تهیه برنامه‌های کارآموزی برای دانش‌آموزان",
		// "تنظیم قوانین و محدودیت‌های ترافیکی برای کاهش تصادفات جاده‌ای",
		// "رعایت حقوق بشر و اصلاح سیستم حق‌الزحمه",
		// "نقش‌آفرینی زنان و ترویج برابری جنسیتی",
		// "راه‌اندازی دفاتر مشاوره پایش و حمایت از رفتار سالم",
		// "راه‌اندازی کلاس‌های آموزشی برای افراد مبتلا به ناتوانی‌های حرکتی",
		"سیاست‌ها و طرح‌هایی برای ایجاد کار در مناطق روستایی",
		"حفاظت از حیوانات همراه با آموزش و ترویج محیط زیستی",
		"تنظیم قوانین نکوهش از نژادی و فرهنگی",
		"حفظ حقوق کارگران و پاسخگویی شرکت‌ها به نیازمندی‌های آن‌ها",
		"ترویج اخلاق و برانگیزش جامعه‌شناختی در مدارس",
		"پاسخگویی دولت به نیازهای آموزشی و بهداشتی مردم",
	}
	// TODO add notifiation date later
	// ! regulations : آیین نامه ها
	D.DB().Create(&M.Law{
		Type:               1,
		Title:              "آیین نامه کانون زبان ایران",
		SessionNumber:      11,
		SessionDate:        time.Date(1989, 4, 12, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/4720",
		NotificationDate:   time.Date(1989, 8, 3, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای جعفری",
	})
	D.DB().Create(&M.Law{
		Type:               1,
		Title:              "آیین نامه ارزشیابی درس تربیت بدنی  ",
		SessionNumber:      553,
		SessionDate:        time.Date(1993, 2, 25, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/11083",
		NotificationDate:   time.Date(1993, 3, 14, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای حسنی",
	})
	D.DB().Create(&M.Law{
		Type:               1,
		Title:              "آیین نامه اعطای دیپلم افتخاری به جانبازان  ",
		SessionNumber:      114,
		SessionDate:        time.Date(1995, 2, 19, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/230",
		NotificationDate:   time.Date(1995, 4, 10, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم اکبری",
	})
	D.DB().Create(&M.Law{
		Type:               1,
		Title:              "آیین نامه  ارزشیابی مدارک تحصیلی مدارش کشور های خارجی   ",
		SessionNumber:      143,
		SessionDate:        time.Date(1997, 12, 3, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/8686",
		NotificationDate:   time.Date(1997, 12, 28, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم کبیری",
	})
	// for i := 0; i < len(regulations); i++ {
	// 	D.DB().Create(&M.Law{
	// 		Type:               1,
	// 		Title:              regulations[i],
	// 		SessionNumber:      143,
	// 		SessionDate:        time.Date(1997, 12, 3, 0, 0, 0, 0, time.UTC),
	// 		NotificationNumber: "120/8686",
	// 		NotificationDate:   time.Date(1997, 12, 28, 0, 0, 0, 0, time.UTC),
	// 		Body:               x,
	// 		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
	// 	})
	// }
	// ! statutes : اساس نامه ها
	D.DB().Create(&M.Law{
		Type:               2,
		Title:              "اساسنامه كانونهای فرهنگی و تربیتی دانشآموزان",
		SessionNumber:      503,
		SessionDate:        time.Date(1990, 2, 19, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/12035",
		NotificationDate:   time.Date(1990, 3, 14, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای حسنی",
	})
	D.DB().Create(&M.Law{
		Type:               2,
		Title:              "اساسنامه مدارس ایثارگران (رزمندگان ، جانبازان و آزادگان)",
		SessionNumber:      514,
		SessionDate:        time.Date(1990, 9, 24, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/9000",
		NotificationDate:   time.Date(1990, 9, 30, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای بینش",
	})
	D.DB().Create(&M.Law{
		Type:               2,
		Title:              "اساسنامه مجتمع آموزشی تطبیقی",
		SessionNumber:      536,
		SessionDate:        time.Date(1992, 1, 30, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/11700",
		NotificationDate:   time.Date(1990, 2, 25, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم علمداری",
	})
	D.DB().Create(&M.Law{
		Type:               2,
		Title:              "اسانامه دبیرستان تربیت بدنی و علوم ورزشی(وابسته به آموزش و پرورش)",
		SessionNumber:      561,
		SessionDate:        time.Date(1993, 10, 7, 0, 0, 0, 0, time.UTC),
		NotificationNumber: "120/11700",
		NotificationDate:   time.Date(1993, 11, 10, 0, 0, 0, 0, time.UTC),
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای کاظمی",
	})
	// for i := 0; i < len(statutes); i++ {
	// 	D.DB().Create(&M.Law{
	// 		Type:               2,
	// 		Title:              statutes[i],
	// 		SessionNumber:      143,
	// 		SessionDate:        time.Date(1997, 12, 3, 0, 0, 0, 0, time.UTC),
	// 		NotificationNumber: "120/8686",
	// 		NotificationDate:   time.Date(1997, 12, 28, 0, 0, 0, 0, time.UTC),
	// 		Body:               x,
	// 		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
	// 	})
	// }
	// ! enactments : مصوبه ها
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "ماده واحده تشکیل ستاد هماهنگی و پشتیبانی اجرای سند تحول",
		SessionNumber:      4515874,
		NotificationNumber: "581/5841",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای کاظم زاده",
	})
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "نظام جامع راهنمایی و مشاوره در آموزش و پرورش",
		SessionNumber:      4514174,
		NotificationNumber: "5522/9542",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای حسنی نژاد",
	})
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "مجموعه مصوبات شورای عالی آموزش و پرورش",
		SessionNumber:      13265,
		NotificationNumber: "581/1238",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "آقای رهنما",
	})
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "آیین نامه تاسیس مدارس اتباع خارجی",
		SessionNumber:      13265,
		NotificationNumber: "581/1238",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم میرسکندری",
	})
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "نحوه جبران عقب ماندگی تحصیلی دانش آموزان در دوران کرونا",
		SessionNumber:      13265,
		NotificationNumber: "581/1238",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم میرحسنی",
	})
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "نواختن زنگ زبان و ادبیات فارسی در مدارس",
		SessionNumber:      13265,
		NotificationNumber: "581/1238",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم حسینی",
	})
	D.DB().Create(&M.Law{
		Type:               3,
		Title:              "ماده واحده تشکیل ستاد هماهنگی و پشتیبانی اجرای سند تحول",
		SessionNumber:      13265,
		NotificationNumber: "581/1238",
		Body:               x,
		Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
		NumberItems:        rand.Intn(20) + 1,
		NumberNotes:        rand.Intn(20) + 1,
		Recommender:        "خانم حسنی",
	})
	for i := 0; i < len(enactments); i++ {
		D.DB().Create(&M.Law{
			Type:               3,
			Title:              enactments[i],
			SessionNumber:      143,
			SessionDate:        time.Date(1997, 12, 3, 0, 0, 0, 0, time.UTC),
			NotificationNumber: "120/8686",
			NotificationDate:   time.Date(1997, 12, 28, 0, 0, 0, 0, time.UTC),
			Body:               x,
			Image:              "https://s2.uupload.ir/files/placeholder-image_ux76.png",
			NumberItems:        rand.Intn(20) + 1,
			NumberNotes:        rand.Intn(20) + 1,
			Recommender:        "خانم علمداری",
		})
	}

}
