package utils

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"time"

	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/session"
	"github.com/gofiber/storage/memory"
)

var (
	Store    *session.Store
	AUTH_KEY string = "authenticated"
	USER_ID  string = "user_id"
)
var Memory *memory.Storage

func NewMemory() *memory.Storage {
	Memory = memory.New(memory.Config{
		GCInterval: 10 * time.Second,
	})
	return Memory
}

// ! generate a 45 long character session id
// ! generated by chatGPT
func GenerateSessionID(secret string) (string, error) {
	// Generate 32 bytes of random data
	idBytes := make([]byte, 32)
	if _, err := rand.Read(idBytes); err != nil {
		return "", err
	}

	// Append the secret code to the bytes
	idBytes = append(idBytes, []byte(secret)...)

	// Hash the bytes using SHA-256
	hashBytes := sha256.Sum256(idBytes)

	// Encode the hash using base64
	id := base64.StdEncoding.EncodeToString(hashBytes[:])

	return id, nil
}

// ! get session from fiber context
func Session(c *fiber.Ctx) *session.Session {
	sess, err := Store.Get(c)
	if err != nil {
		panic(err)
	}
	return sess
}
